#pragma once

namespace geyz
{
	void* funt = nullptr;
	void* funtburbur = nullptr;
	void* funtengine = nullptr;

	FName HeadName;
	FName RootName;
	FName NeckName;
	FName LowerNeckName;
	FName ChestName;
	FName PelvisName;
	FName Upperarm_lName;
	FName Upperarm_rName;
	FName Lowerarm_lName;
	FName Lowerarm_rName;
	FName Hand_lName;
	FName Hand_rName;
	FName Thigh_lName;
	FName Thigh_rName;
	FName Calf_lName;
	FName Calf_rName;
	FName LowerCalf_lName;
	FName LowerCalf_rName;
	FName Foot_lName;
	FName Foot_rName;
	FName Toe_lName;
	FName Toe_rName;

	FKey MouseScrollUp;
	FKey MouseScrollDown;
	FKey MouseWheelAxis;
	FKey LeftMouseButton;
	FKey RightMouseButton;
	FKey MiddleMouseButton;
	FKey ThumbMouseButton;
	FKey ThumbMouseButton2;
	FKey BackSpace;
	FKey Tab;
	FKey Enter;
	FKey Pause;
	FKey CapsLock;
	FKey Escape;
	FKey SpaceBar;
	FKey PageUp;
	FKey PageDown;
	FKey End;
	FKey Home;
	FKey Left;
	FKey Up;
	FKey Right;
	FKey Down;
	FKey Insert;
	FKey Delete;
	FKey Zero;
	FKey One;
	FKey Two;
	FKey Three;
	FKey Four;
	FKey Five;
	FKey Six;
	FKey Seven;
	FKey Eight;
	FKey Nine;
	FKey A;
	FKey B;
	FKey C;
	FKey D;
	FKey E;
	FKey F;
	FKey G;
	FKey H;
	FKey I;
	FKey J;
	FKey K;
	FKey L;
	FKey M;
	FKey N;
	FKey O;
	FKey P;
	FKey Q;
	FKey R;
	FKey S;
	FKey T;
	FKey U;
	FKey V;
	FKey W;
	FKey X;
	FKey Y;
	FKey Z;
	FKey NumPadZero;
	FKey NumPadOne;
	FKey NumPadTwo;
	FKey NumPadThree;
	FKey NumPadFour;
	FKey NumPadFive;
	FKey NumPadSix;
	FKey NumPadSeven;
	FKey NumPadEight;
	FKey NumPadNine;
	FKey Multiply;
	FKey Add;
	FKey Subtract;
	FKey Decimal;
	FKey Divide;
	FKey F1;
	FKey F2;
	FKey F3;
	FKey F4;
	FKey F5;
	FKey F6;
	FKey F7;
	FKey F8;
	FKey F9;
	FKey F10;
	FKey F11;
	FKey F12;
	FKey NumLock;
	FKey ScrollLock;
	FKey LeftShift;
	FKey RightShift;
	FKey LeftControl;
	FKey RightControl;
	FKey LeftAlt;
	FKey RightAlt;
	FKey LeftCommand;
	FKey RightCommand;
	FKey Semicolon;
	FKey Equals;
	FKey Comma;
	FKey Underscore;
	FKey Hyphen;
	FKey Period;
	FKey Slash;
	FKey Tilde;
	FKey LeftBracket;
	FKey LeftParantheses;
	FKey Backslash;
	FKey RightBracket;
	FKey RightParantheses;
	FKey Apostrophe;
	FKey Quote;
	FKey Asterix;
	FKey Ampersand;
	FKey Caret;
	FKey Dollar;
	FKey Exclamation;
	FKey Colon;
	FKey Section;
	FKey Gamepad_Left2D;
	FKey Gamepad_LeftX;
	FKey Gamepad_LeftY;
	FKey Gamepad_Right2D;
	FKey Gamepad_RightX;
	FKey Gamepad_RightY;
	FKey Gamepad_LeftTriggerAxis;
	FKey Gamepad_RightTriggerAxis;
	FKey Gamepad_LeftThumbstick;
	FKey Gamepad_RightThumbstick;
	FKey Gamepad_Special_Left;
	FKey Gamepad_Special_Left_X;
	FKey Gamepad_Special_Left_Y;
	FKey Gamepad_Special_Right;
	FKey Gamepad_FaceButton_Bottom;
	FKey Gamepad_FaceButton_Right;
	FKey Gamepad_FaceButton_Left;
	FKey Gamepad_FaceButton_Top;
	FKey Gamepad_LeftShoulder;
	FKey Gamepad_RightShoulder;
	FKey Gamepad_LeftTrigger;
	FKey Gamepad_RightTrigger;
	FKey Gamepad_DPad_Up;
	FKey Gamepad_DPad_Down;
	FKey Gamepad_DPad_Right;
	FKey Gamepad_DPad_Left;
	FKey Gamepad_LeftStick_Up;
	FKey Gamepad_LeftStick_Down;
	FKey Gamepad_LeftStick_Right;
	FKey Gamepad_LeftStick_Left;
	FKey Gamepad_RightStick_Up;
	FKey Gamepad_RightStick_Down;
	FKey Gamepad_RightStick_Right;
	FKey Gamepad_RightStick_Left;

	FKey AKey;
	FKey FLKey;
	FKey TKey;
	FKey FLKeyBoost;
	FKey WSteal;
	FKey LPicker;
	FKey LDestroyer;
	FKey MToggle;
	FKey PToggle;

	FName InsKe(FString Keyname) {
		return STATIC_Conv_StringToName(Keyname);
	}

	void operamom(bool issq = false, bool isnew = false) {
		if (issq)
			funt = FindMyObject(xMe(L"BurbankSmall:BurbankSmall"));
		else if (isnew)
			funt = FindMyObject(xMe(L"HeadingNow:HeadingNow"));
		else
			funt = FindMyObject(xMe(L"Roboto:Roboto"));

		funtburbur = FindMyObject(xMe(L"Burbank:Burbank"));
		funtengine = FindMyObject(xMe(L"Roboto:Roboto"));

		// Special keys stuff
		MouseScrollUp = FKey(InsKe(xMe(L"MouseScrollUp")));
		MouseScrollDown = FKey(InsKe(xMe(L"MouseScrollDown")));
		MouseWheelAxis = FKey(InsKe(xMe(L"MouseWheelAxis")));
		LeftMouseButton = FKey(InsKe(xMe(L"LeftMouseButton")));
		RightMouseButton = FKey(InsKe(xMe(L"RightMouseButton")));
		MiddleMouseButton = FKey(InsKe(xMe(L"MiddleMouseButton")));
		ThumbMouseButton = FKey(InsKe(xMe(L"ThumbMouseButton")));
		ThumbMouseButton2 = FKey(InsKe(xMe(L"ThumbMouseButton2")));
		BackSpace = FKey(InsKe(xMe(L"BackSpace")));
		Tab = FKey(InsKe(xMe(L"Tab")));
		Enter = FKey(InsKe(xMe(L"Enter")));
		Pause = FKey(InsKe(xMe(L"Pause")));
		CapsLock = FKey(InsKe(xMe(L"CapsLock")));
		Escape = FKey(InsKe(xMe(L"Escape")));
		SpaceBar = FKey(InsKe(xMe(L"SpaceBar")));
		PageUp = FKey(InsKe(xMe(L"PageUp")));
		PageDown = FKey(InsKe(xMe(L"PageDown")));
		End = FKey(InsKe(xMe(L"End")));
		Home = FKey(InsKe(xMe(L"Home")));
		Left = FKey(InsKe(xMe(L"Left")));
		Up = FKey(InsKe(xMe(L"Up")));
		Right = FKey(InsKe(xMe(L"Right")));
		Down = FKey(InsKe(xMe(L"Down")));
		Insert = FKey(InsKe(xMe(L"Insert")));
		Delete = FKey(InsKe(xMe(L"Delete")));
		Zero = FKey(InsKe(xMe(L"Zero")));
		One = FKey(InsKe(xMe(L"One")));
		Two = FKey(InsKe(xMe(L"Two")));
		Three = FKey(InsKe(xMe(L"Three")));
		Four = FKey(InsKe(xMe(L"Four")));
		Five = FKey(InsKe(xMe(L"Five")));
		Six = FKey(InsKe(xMe(L"Six")));
		Seven = FKey(InsKe(xMe(L"Seven")));
		Eight = FKey(InsKe(xMe(L"Eight")));
		Nine = FKey(InsKe(xMe(L"Nine")));
		A = FKey(InsKe(xMe(L"A")));
		B = FKey(InsKe(xMe(L"B")));
		C = FKey(InsKe(xMe(L"C")));
		D = FKey(InsKe(xMe(L"D")));
		E = FKey(InsKe(xMe(L"E")));
		F = FKey(InsKe(xMe(L"F")));
		G = FKey(InsKe(xMe(L"G")));
		H = FKey(InsKe(xMe(L"H")));
		I = FKey(InsKe(xMe(L"I")));
		J = FKey(InsKe(xMe(L"J")));
		K = FKey(InsKe(xMe(L"K")));
		L = FKey(InsKe(xMe(L"L")));
		M = FKey(InsKe(xMe(L"M")));
		N = FKey(InsKe(xMe(L"N")));
		O = FKey(InsKe(xMe(L"O")));
		P = FKey(InsKe(xMe(L"P")));
		Q = FKey(InsKe(xMe(L"Q")));
		R = FKey(InsKe(xMe(L"R")));
		S = FKey(InsKe(xMe(L"S")));
		T = FKey(InsKe(xMe(L"T")));
		U = FKey(InsKe(xMe(L"U")));
		V = FKey(InsKe(xMe(L"V")));
		W = FKey(InsKe(xMe(L"W")));
		X = FKey(InsKe(xMe(L"X")));
		Y = FKey(InsKe(xMe(L"Y")));
		Z = FKey(InsKe(xMe(L"Z")));
		NumPadZero = FKey(InsKe(xMe(L"NumPadZero")));
		NumPadOne = FKey(InsKe(xMe(L"NumPadOne")));
		NumPadTwo = FKey(InsKe(xMe(L"NumPadTwo")));
		NumPadThree = FKey(InsKe(xMe(L"NumPadThree")));
		NumPadFour = FKey(InsKe(xMe(L"NumPadFour")));
		NumPadFive = FKey(InsKe(xMe(L"NumPadFive")));
		NumPadSix = FKey(InsKe(xMe(L"NumPadSix")));
		NumPadSeven = FKey(InsKe(xMe(L"NumPadSeven")));
		NumPadEight = FKey(InsKe(xMe(L"NumPadEight")));
		NumPadNine = FKey(InsKe(xMe(L"NumPadNine")));
		Multiply = FKey(InsKe(xMe(L"Multiply")));
		Add = FKey(InsKe(xMe(L"Add")));
		Subtract = FKey(InsKe(xMe(L"Subtract")));
		Decimal = FKey(InsKe(xMe(L"Decimal")));
		Divide = FKey(InsKe(xMe(L"Divide")));
		F1 = FKey(InsKe(xMe(L"F1")));
		F2 = FKey(InsKe(xMe(L"F2")));
		F3 = FKey(InsKe(xMe(L"F3")));
		F4 = FKey(InsKe(xMe(L"F4")));
		F5 = FKey(InsKe(xMe(L"F5")));
		F6 = FKey(InsKe(xMe(L"F6")));
		F7 = FKey(InsKe(xMe(L"F7")));
		F8 = FKey(InsKe(xMe(L"F8")));
		F9 = FKey(InsKe(xMe(L"F9")));
		F10 = FKey(InsKe(xMe(L"F10")));
		F11 = FKey(InsKe(xMe(L"F11")));
		F12 = FKey(InsKe(xMe(L"F12")));
		NumLock = FKey(InsKe(xMe(L"NumLock")));
		ScrollLock = FKey(InsKe(xMe(L"ScrollLock")));
		LeftShift = FKey(InsKe(xMe(L"LeftShift")));
		RightShift = FKey(InsKe(xMe(L"RightShift")));
		LeftControl = FKey(InsKe(xMe(L"LeftControl")));
		RightControl = FKey(InsKe(xMe(L"RightControl")));
		LeftAlt = FKey(InsKe(xMe(L"LeftAlt")));
		RightAlt = FKey(InsKe(xMe(L"RightAlt")));
		LeftCommand = FKey(InsKe(xMe(L"LeftCommand")));
		RightCommand = FKey(InsKe(xMe(L"RightCommand")));
		Semicolon = FKey(InsKe(xMe(L"Semicolon")));
		Equals = FKey(InsKe(xMe(L"Equals")));
		Comma = FKey(InsKe(xMe(L"Comma")));
		Underscore = FKey(InsKe(xMe(L"Underscore")));
		Hyphen = FKey(InsKe(xMe(L"Hyphen")));
		Period = FKey(InsKe(xMe(L"Period")));
		Slash = FKey(InsKe(xMe(L"Slash")));
		Tilde = FKey(InsKe(xMe(L"Tilde")));
		LeftBracket = FKey(InsKe(xMe(L"LeftBracket")));
		LeftParantheses = FKey(InsKe(xMe(L"LeftParantheses")));
		Backslash = FKey(InsKe(xMe(L"Backslash")));
		RightBracket = FKey(InsKe(xMe(L"RightBracket")));
		RightParantheses = FKey(InsKe(xMe(L"RightParantheses")));
		Apostrophe = FKey(InsKe(xMe(L"Apostrophe")));
		Quote = FKey(InsKe(xMe(L"Quote")));
		Asterix = FKey(InsKe(xMe(L"Asterix")));
		Ampersand = FKey(InsKe(xMe(L"Ampersand")));
		Caret = FKey(InsKe(xMe(L"Caret")));
		Dollar = FKey(InsKe(xMe(L"Dollar")));
		Exclamation = FKey(InsKe(xMe(L"Exclamation")));
		Colon = FKey(InsKe(xMe(L"Colon")));
		Section = FKey(InsKe(xMe(L"Section")));
		Gamepad_Left2D = FKey(InsKe(xMe(L"Gamepad_Left2D")));
		Gamepad_LeftX = FKey(InsKe(xMe(L"Gamepad_LeftX")));
		Gamepad_LeftY = FKey(InsKe(xMe(L"Gamepad_LeftY")));
		Gamepad_Right2D = FKey(InsKe(xMe(L"Gamepad_Right2D")));
		Gamepad_RightX = FKey(InsKe(xMe(L"Gamepad_RightX")));
		Gamepad_RightY = FKey(InsKe(xMe(L"Gamepad_RightY")));
		Gamepad_LeftTriggerAxis = FKey(InsKe(xMe(L"Gamepad_LeftTriggerAxis")));
		Gamepad_RightTriggerAxis = FKey(InsKe(xMe(L"Gamepad_RightTriggerAxis")));
		Gamepad_LeftThumbstick = FKey(InsKe(xMe(L"Gamepad_LeftThumbstick")));
		Gamepad_RightThumbstick = FKey(InsKe(xMe(L"Gamepad_RightThumbstick")));
		Gamepad_Special_Left = FKey(InsKe(xMe(L"Gamepad_Special_Left")));
		Gamepad_Special_Left_X = FKey(InsKe(xMe(L"Gamepad_Special_Left_X")));
		Gamepad_Special_Left_Y = FKey(InsKe(xMe(L"Gamepad_Special_Left_Y")));
		Gamepad_Special_Right = FKey(InsKe(xMe(L"Gamepad_Special_Right")));
		Gamepad_FaceButton_Bottom = FKey(InsKe(xMe(L"Gamepad_FaceButton_Bottom")));
		Gamepad_FaceButton_Right = FKey(InsKe(xMe(L"Gamepad_FaceButton_Right")));
		Gamepad_FaceButton_Left = FKey(InsKe(xMe(L"Gamepad_FaceButton_Left")));
		Gamepad_FaceButton_Top = FKey(InsKe(xMe(L"Gamepad_FaceButton_Top")));
		Gamepad_LeftShoulder = FKey(InsKe(xMe(L"Gamepad_LeftShoulder")));
		Gamepad_RightShoulder = FKey(InsKe(xMe(L"Gamepad_RightShoulder")));
		Gamepad_LeftTrigger = FKey(InsKe(xMe(L"Gamepad_LeftTrigger")));
		Gamepad_RightTrigger = FKey(InsKe(xMe(L"Gamepad_RightTrigger")));
		Gamepad_DPad_Up = FKey(InsKe(xMe(L"Gamepad_DPad_Up")));
		Gamepad_DPad_Down = FKey(InsKe(xMe(L"Gamepad_DPad_Down")));
		Gamepad_DPad_Right = FKey(InsKe(xMe(L"Gamepad_DPad_Right")));
		Gamepad_DPad_Left = FKey(InsKe(xMe(L"Gamepad_DPad_Left")));
		Gamepad_LeftStick_Up = FKey(InsKe(xMe(L"Gamepad_LeftStick_Up")));
		Gamepad_LeftStick_Down = FKey(InsKe(xMe(L"Gamepad_LeftStick_Down")));
		Gamepad_LeftStick_Right = FKey(InsKe(xMe(L"Gamepad_LeftStick_Right")));
		Gamepad_LeftStick_Left = FKey(InsKe(xMe(L"Gamepad_LeftStick_Left")));
		Gamepad_RightStick_Up = FKey(InsKe(xMe(L"Gamepad_RightStick_Up")));
		Gamepad_RightStick_Down = FKey(InsKe(xMe(L"Gamepad_RightStick_Down")));
		Gamepad_RightStick_Right = FKey(InsKe(xMe(L"Gamepad_RightStick_Right")));
		Gamepad_RightStick_Left = FKey(InsKe(xMe(L"Gamepad_RightStick_Left")));

		AKey = RightMouseButton;
		TKey = LeftShift;
		MToggle = Insert;

		HeadName = InsKe(xMe(L"head"));
		RootName = InsKe(xMe(L"Root"));
		NeckName = InsKe(xMe(L"neck_01"));
		LowerNeckName = InsKe(xMe(L"clavicle_l"));
		ChestName = InsKe(xMe(L"spine_03"));
		PelvisName = InsKe(xMe(L"pelvis"));
		ChestName = InsKe(xMe(L"spine_03"));
		Upperarm_lName = InsKe(xMe(L"upperarm_l"));
		Upperarm_rName = InsKe(xMe(L"upperarm_r"));
		Lowerarm_lName = InsKe(xMe(L"lowerarm_l"));
		Lowerarm_rName = InsKe(xMe(L"lowerarm_r"));
		Hand_lName = InsKe(xMe(L"hand_l"));
		Hand_rName = InsKe(xMe(L"hand_r"));
		Thigh_lName = InsKe(xMe(L"thigh_l"));
		Thigh_rName = InsKe(xMe(L"thigh_r"));
		Calf_lName = InsKe(xMe(L"calf_l"));
		Calf_rName = InsKe(xMe(L"calf_r"));
		LowerCalf_lName = InsKe(xMe(L"calf_twist_02_l"));
		LowerCalf_rName = InsKe(xMe(L"calf_twist_02_r"));
		Foot_lName = InsKe(xMe(L"ik_foot_l"));
		Foot_rName = InsKe(xMe(L"ik_foot_r"));
		Toe_lName = InsKe(xMe(L"ball_l"));
		Toe_rName = InsKe(xMe(L"ball_r"));
	}
}